### ISSUE TITLE
O:9 interpretation

### ISSUE THREAD

**Issue by ATML-TD** [denglab/SeqSero2#15]
Hello,

Most of my Enteritidis genomes are identified as Hillingdon due to detection of the O-9,46_wbaV__1002 sequence with no apparent link to the match score, , e.g.:
****
Output_directory:	SeqSero_result_08_26_2019_12_42_017562833
Input files:	Salm201905696_S134_R1.fastq.gz
O antigen prediction:	9,46
H1 antigen prediction(fliC):	g,m
H2 antigen prediction(fljB):	-
Predicted subspecies:	I
Predicted antigenic profile:	9,46:g,m:-
Predicted serotype:	Hillingdon
**associated log:**
O_scores:
O-1,3,19_not_in_3,10__130	73.07692307692307
O-9,46_wbaV__1002	54.09836065573771
Special_scores:
uniqmers_I	100.0
gntR-family-regulatory-protein_dt-positive__291	100.0
gntR-family-regulatory-protein_dt-negative__291	89.81132075471699
allmers	12.978168162433965
sdf_I_AF370707__333	91.20521172638436
sdf-I_AF370707__333	91.20521172638436

**##other genome**
Output_directory:	SeqSero_result_08_26_2019_12_42_014760921
Input files:	Salm201905700_S136_R1.fastq.gz
O antigen prediction:	9
H1 antigen prediction(fliC):	g,m
H2 antigen prediction(fljB):	-
Predicted subspecies:	I
Predicted antigenic profile:	9:g,m:-
Predicted serotype:	Enteritidis
Note: sdf gene detected.
**associated log:**
O_scores:
O-1,3,19_not_in_3,10__130	73.07692307692307
O-9,46_wbaV__1002	80.84016393442623
Special_scores:
uniqmers_I	100.0
gntR-family-regulatory-protein_dt-positive__291	96.98113207547169
gntR-family-regulatory-protein_dt-negative__291	86.79245283018868
allmers	13.15002227738527
sdf_I_AF370707__333	91.20521172638436
sdf-I_AF370707__333	91.20521172638436

I dont really get how the O:9 is determined.
Thx for your help

**Comment by LSTUGA** [comment]
Hey, 

Thanks for asking. SeqSero2 uses the gene O-9,46_wbaV__1002  to differenticate O:9,46 and O:9. For genome Salm201905696, the match score of O-9,46_wbaV__1002 is too low to be called (default minimum match score is 70), which would influence the final prediction output. The low match score of the gene wbaV could be caused by unsufficient sequencing coverage; or, it's also possible that the wbaV in your Enteritidis genomes is a new allele that differs from the one in our allele database.
You can share your genomes to us and we will be happy to do the troubleshooting and try to fix the issue.

Thanks!
