### ISSUE TITLE
USAGE in README does not reflect default mode in v1.0.0 release

### ISSUE THREAD

**Issue by kapsakcj** [denglab/SeqSero2#7]
In the USAGE section of the readme, it states that the default mode is allele mode:
```
Usage: SeqSero2_package.py 

-m <string> (which workflow to apply, 'a'(allele micro-assembly), 'k'(raw reads and genome assembly k-mer), default=a)
```
Although in the SeqSero2 v1.0.0 release, it shows that the k-mer mode is default (and I believe runs k-mer mode as default, too):
```
usage: SeqSero2_package.py -t <data_type> -m <mode> -i <input_data> [-p <number of threads>] [-b <BWA_algorithm>]

Developper: Shaokang Zhang (zskzsk@uga.edu), Hendrik C Den-Bakker (Hendrik.DenBakker@uga.edu) and Xiangyu Deng (xdeng@uga.edu)

Contact email:seqsero@gmail.com

optional arguments:
  -h, --help        show this help message and exit
  -i I [I ...]      <string>: path/to/input_data
  -t {1,2,3,4,5,6}  <int>: '1'(pair-end reads, interleaved),'2'(pair-end
                    reads, seperated),'3'(single-end reads),
                    '4'(assembly),'5'(nanopore fasta),'6'(nanopore fastq)
  -b {sam,mem}      <string>: mode for mapping, 'sam'(bwa samse/sampe),
                    'mem'(bwa mem), default=mem
  -p P              <int>: threads used for mapping mode, if p>4, only 4
                    threads will be used for assembly, default=1
  -m {k,a}          <string>: 'k'(kmer mode), 'a'(allele mode), default=k

```

**Comment by denglab** [comment]
Curtis,

Since V1.0.0, we recommend allele micro assembly as the default workflow. According to our evaluation, it is more accurate than K-mer based workflows and provides additional benefit of potential inter-serotype contamination detection. K-mer is faster and best suited for high throughout applications.

Best,
Xiangyu

Sent from my iPhone

On May 7, 2019, at 2:22 PM, Curtis Kapsak <notifications@github.com<mailto:notifications@github.com>> wrote:


In the USAGE section of the readme, it states that the default mode is allele mode:

Usage: SeqSero2_package.py

-m <string> (which workflow to apply, 'a'(allele micro-assembly), 'k'(raw reads and genome assembly k-mer), default=a)


Although in the SeqSero2 v1.0.0 release, it shows that the k-mer mode is default (and I believe runs k-mer mode as default, too):

usage: SeqSero2_package.py -t <data_type> -m <mode> -i <input_data> [-p <number of threads>] [-b <BWA_algorithm>]

Developper: Shaokang Zhang (zskzsk@uga.edu<mailto:zskzsk@uga.edu>), Hendrik C Den-Bakker (Hendrik.DenBakker@uga.edu<mailto:Hendrik.DenBakker@uga.edu>) and Xiangyu Deng (xdeng@uga.edu<mailto:xdeng@uga.edu>)

Contact email:seqsero@gmail.com<mailto:seqsero@gmail.com>

optional arguments:
  -h, --help        show this help message and exit
  -i I [I ...]      <string>: path/to/input_data
  -t {1,2,3,4,5,6}  <int>: '1'(pair-end reads, interleaved),'2'(pair-end
                    reads, seperated),'3'(single-end reads),
                    '4'(assembly),'5'(nanopore fasta),'6'(nanopore fastq)
  -b {sam,mem}      <string>: mode for mapping, 'sam'(bwa samse/sampe),
                    'mem'(bwa mem), default=mem
  -p P              <int>: threads used for mapping mode, if p>4, only 4
                    threads will be used for assembly, default=1
  -m {k,a}          <string>: 'k'(kmer mode), 'a'(allele mode), default=k

**Comment by kapsakcj** [comment]
OK, thanks for clarifying, Xiangyu. It might be a good idea to edit the help options that appear when you run `SeqSero2_package.py` to reflect your recommendation.

Best,
Curtis
